version: "3"

services:
  server:
    build: .
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    command: >
      sh -c "pipenv run python src/manage.py migrate
      && pipenv run python src/manage.py runserver 0.0.0.0:8000"
  watch_transactions:
    build: .
    volumes:
      - .:/code/
    command: >
      sh -c "pipenv run python src/manage.py watch_transactions"
  check_trustlines:
    build: .
    volumes:
      - .:/code/
    command: >
      sh -c "pipenv run python src/manage.py check_trustlines --loop"
